[package]
name = "message-board-r-printer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
escpos = { version = "0.13.1", default-features = false, features = ["native_usb", "usb", "codes_2d"] }
nusb = "0.1.12"
inquire = "0.7.5"